-keep class org.apache.poi.** { *; }
-keep class org.apache.xmlbeans.** { *; }
-keep class com.tom_roush.** { *; }
-keep class com.google.mlkit.** { *; }
-dontwarn org.apache.poi.**
-dontwarn org.apache.xmlbeans.**
-dontwarn java.awt.**
-dontwarn java.lang.management.**
-dontwarn java.beans.**
-dontwarn javax.xml.**
-dontwarn javax.management.**
